ingress:
    host: keycloak1.mendix.local
keycloak:
    replicas: 1
    admin:
        user: admin
        password: password
postgres:
    host: postgres
    port: 5432
    admin:
        user: admin
        password: password