ingress:
    host: keycloak1.mendix.local
keycloak:
    replicas: 2
    admin:
        user: admin
        password: password
local: true
namespace: pib-ns
postgres:
    host: postgres
    port: 5432
    admin:
        user: admin
        password: password