apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
  externalIPs:
    - 172.18.228.94