apiVersion: v1
entries:
  keycloakhelm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-12-19T18:31:51.190821+05:30"
    description: A Helm chart for Kubernetes
    digest: f9cd65e190cac7f9614fbffde80a575eb92345cbba207677a211d2b721bd5807
    name: keycloakhelm
    type: application
    urls:
    - keycloakhelm-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-19T18:31:51.185737+05:30"
