apiVersion: v1
entries:
  keycloakhelm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-12-19T17:16:40.446576+05:30"
    description: A Helm chart for Kubernetes
    digest: 27f951420a9f6de7f92ef7cb6c63b5d2d2565ec8cfc343e585de84883a8acd4a
    name: keycloakhelm
    type: application
    urls:
    - keycloakhelm-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-19T17:16:40.440039+05:30"
