apiVersion: v1
entries:
  keycloakhelm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-12-20T10:19:19.326027+05:30"
    description: A Helm chart for Kubernetes
    digest: fe5dd6668bab79140fdd1d1fac13146470725e79a2f32abe9ef586415d89ac7d
    name: keycloakhelm
    type: application
    urls:
    - keycloakhelm-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-20T10:19:19.324258+05:30"
