apiVersion: privatecloud.mendix.com/v1alpha1
kind: MendixApp
metadata:
  name: pibconfigurator
spec:
  database: # Specification of Database CR
    servicePlan: {{ .Values.pibConfiguratorMendixRuntime.database.servicePlan }}
  storage: # Specification of Storage CR
    servicePlan: {{ .Values.pibConfiguratorMendixRuntime.storage.servicePlan }}
  mendixRuntimeVersion: 9.12.7.54456 # Mendix version to use for placeholder runtime image
  sourceURL: {{ .Values.pibConfiguratorMendixRuntime.sourceURL }} # URL of App's source MDA
  appURL: {{ .Values.pibConfiguratorMendixRuntime.appURL }} # URL to access the app
  tls: # Optional, can be omitted : set a custom TLS configuration, overriding the default operator configuration
    # Enable or disable TLS for the app
    enableTLS: true    
  replicas: 1 # Number of replicas, set to 0 to stop all replicas
  resources: # Optional, can be omitted : set resources for Mendix Runtime container 
    limits: # Upper limit - process will be stopped if it tries to use more
      cpu: 500m # 500 millicores - half of a vCPU
      memory: 512Mi # 512 megabytes - suitable for small-scale non-production apps
    requests: # Lower limit - needs at least these resources
      cpu: 100m
      memory: 512Mi
  runtimeDeploymentPodAnnotations: # Optional, can be omitted : set custom annotations for Mendix Runtime Pods
    # example: inject the Linkerd proxy sidecar
    linkerd.io/inject: enabled
  runtime: # Configuration of the Mendix Runtime
    logAutosubscribeLevel: INFO # Default logging level
    mxAdminPassword: {{ .Values.pibConfiguratorMendixRuntime.mxAdminPassword }} # base64 encoded password for MendixAdmin user. In this example, 'Welc0me!'; can be left empty keep password unchanged
    dtapMode: P # Security & runtime mode: P for production, D for development
    logLevels: # Optional, can be omitted : set custom log levels for specific nodes
      NodeOne: CRITICAL
      NodeTwo: DEBUG
    microflowConstants: # Optional, can be omitted : set values for microflow constants
      PIBConfigurator.AdminClientID: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.adminClientID }}
      PIBConfigurator.LogNode: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.logNode }}
      PIBConfigurator.Password: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.password }}
      PIBConfigurator.Realm: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.realm }}
      PIBConfigurator.ServerBaseUrl: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.serverBaseUrl }}
      PIBConfigurator.Username: {{ .Values.pibConfiguratorMendixRuntime.microflowConstants.username }}
      Administration.EnableMendixSSOUserMigration: "False"
      NanoflowCommons.Nanoflow_Commons_Version: "2.1.0"
      WebActions.WebActions_Version: "2.4.0"
    scheduledEventExecution: NONE # Optional, can be omitted: specify which scheduled events should be enabled: ALL/NONE/SPECIFIED
    # Mendix Runtime Jetty options, in JSON format; validated and applied by the mx-m2ee-sidecar container
    jettyOptions: |-
      {
        "max_form_content_size": 10485760,
        "use_blocking_connector": false
      }      
    # All custom Mendix Runtime parameters go here, in JSON format; validated and applied by the mx-m2ee-sidecar container
    customConfiguration: |-
      {
        "ApplicationRootUrl": {{ .Values.pibConfiguratorMendixRuntime.applicationRootUrl }}
      }      
